version: "3.9"
networks:
  deploy-guide-dev:
    driver: bridge
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: developforum
    ports:
      - "8080:8080"
    networks:
      - deploy-guide-dev
    depends_on:
      - developforum_db
    
    env_file:
      - .env
    

  developforum_db:
    restart: always
    container_name: developforum_db
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: DevelopForum
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - developforum_db_data:/var/lib/postgresql/data



volumes:
  developforum_db_data:
